# Generated by Django 2.2.11 on 2020-03-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField(verbose_name='Mensaje Blog')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
